# Machine Interface Web
# Lancer avec: docker compose -f docker-compose.web.yml up -d --build

services:
  web-ui:
    build:
      context: ..
      dockerfile: services/web-ui/Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY_WEB:-change-me-web}
      AUTH_INTERNAL_URL: http://${AUTH_IP:-localhost}:8000
      API_INTERNAL_URL: http://${CATALOG_IP:-localhost}:8001
      PUBLIC_AUTH_URL: http://${AUTH_IP:-localhost}:8000
      PUBLIC_API_URL: http://${CATALOG_IP:-localhost}:8001
      CURRENCY_CODE: ${CURRENCY_CODE:-DZD}
      CURRENCY_SYMBOL: ${CURRENCY_SYMBOL:-DA}
      CONSUL_HTTP_ADDR: http://${MASTER_IP:-localhost}:8500
      SERVICE_NAME: web-ui
      SERVICE_PORT: "8000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.pharm-web-prof.rule=Host(`172.20.10.2`) || Host(`localhost`) || PathPrefix(`/`)
      - traefik.http.services.pharm-web.loadbalancer.server.port=8000
    volumes:
      - ../services/web-ui:/app
    networks:
      - pharm_net

networks:
  pharm_net:
    driver: bridge
