# Generated by Django 4.2.16 on 2026-03-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_order_order_number_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_ai_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='user_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
