# Generated by Django 4.2.16 on 2026-03-26 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_is_ai_recommended_product_user_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user_id', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='likes',
                    to='catalog.product'
                )),
            ],
            options={
                'verbose_name': 'Product Like',
                'verbose_name_plural': 'Product Likes',
            },
        ),

        migrations.AddConstraint(
            model_name='productlike',
            constraint=models.UniqueConstraint(
                fields=('product', 'auth_user_id'),
                name='unique_product_user_like'
            ),
        ),
    ]