# Generated by Django 4.2.16 on 2026-03-26 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlike',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='user_recommendations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user_id', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Recommendation',
                'verbose_name_plural': 'Product Recommendations',
            },
        ),
        migrations.AddConstraint(
            model_name='productrecommendation',
            constraint=models.UniqueConstraint(fields=('product', 'auth_user_id'), name='unique_product_user_recommendation'),
        ),
    ]
