# Generated by Django 4.2.16 on 2026-03-26 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productlike_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto_shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user_id', models.PositiveIntegerField(db_index=True)),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1⭐'), (2, '2⭐'), (3, '3⭐'), (4, '4⭐'), (5, '5⭐')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Product Rating',
                'verbose_name_plural': 'Product Ratings',
            },
        ),
        migrations.AddConstraint(
            model_name='productrating',
            constraint=models.UniqueConstraint(fields=('product', 'auth_user_id'), name='unique_product_user_rating'),
        ),
    ]
