# Generated by Django 4.2.16 on 2026-03-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_fields_for_csv_import'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrating',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productrecommendation',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='productlike',
            name='unique_product_user_like',
        ),
        migrations.RemoveConstraint(
            model_name='productrating',
            name='unique_product_user_rating',
        ),
        migrations.RemoveConstraint(
            model_name='productrecommendation',
            name='unique_product_user_recommendation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_phone',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productrating',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='auth_user_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('SHIPPED', 'Expédiée'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, '0⭐'), (1, '1⭐'), (2, '2⭐'), (3, '3⭐'), (4, '4⭐'), (5, '5⭐')]),
        ),
        migrations.AddConstraint(
            model_name='productlike',
            constraint=models.UniqueConstraint(fields=('auth_user_id', 'product'), name='unique_user_product_like'),
        ),
        migrations.AddConstraint(
            model_name='productrating',
            constraint=models.UniqueConstraint(fields=('auth_user_id', 'product'), name='unique_user_product_rating'),
        ),
        migrations.AddConstraint(
            model_name='productrecommendation',
            constraint=models.UniqueConstraint(fields=('auth_user_id', 'product'), name='unique_user_product_recommendation'),
        ),
    ]
