# Generated by Django 4.2.16 on 2026-03-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pharmacy_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pharmacy_wilaya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='auth_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
