# Generated by Django 4.2.16 on 2026-03-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_image'),
        ('catalog', '0012_alter_product_sku_alter_product_slug'),
    ]

    operations = [
    ]
